Get videos by Author and Test done
OscarArnedo/LS2-protube-grup9 pull request #87
Opened 2024-11-20 17:59 UTC by LuisAcostaSicilia

Si el author no tiene videos, como no tenemos el método aun de crear video, he decidido devolver una lista vacía. 

El test esta hecho en función ha esto.

2024-11-23 09:23 UTC, OscarArnedo commented on backend/src/main/java/com/tecnocampus/LS2/protube_back/persistance/VideoRepository.java
Ya tienes un método que le pase el Owner, para que haces otro igual que le pasas el OwnerId si en el service tienes el owner entero?

2024-11-23 09:23 UTC, OscarArnedo commented on backend/src/test/java/com/tecnocampus/LS2/protube_back/ProtubeBackApplicationTests.java
Un poco raro el "if (!videos.isEmpty())", por ahora está bien, pero cuando añadamos la funcionalidad de añadir videos se tendrá que modificar

2024-11-23 09:24 UTC, OscarArnedo requested changes
Modificar lo comentado en el repository

2024-11-23 16:42 UTC, LuisAcostaSicilia commented on backend/src/main/java/com/tecnocampus/LS2/protube_back/persistance/VideoRepository.java
Tienes razón, ya lo he modificado. Fue por un error y estuve probando y me olvide de modificar-lo. Bien visto!

2024-11-23 16:44 UTC, giselabusquets25 approved these changes
Ben vist Oscar i bon canvi!

2024-11-23 16:47 UTC, LuisAcostaSicilia commented on backend/src/test/java/com/tecnocampus/LS2/protube_back/ProtubeBackApplicationTests.java
Okey ja ho mirarem quan ho necesitem.

2024-11-23 16:50 UTC, giselabusquets25 approved these changes

2024-11-25 15:08 UTC, alahoraT approved these changes

2024-11-25 15:08 UTC, OscarArnedo approved these changes
perfect

2024-11-25 15:08 UTC, merged